//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityApplicationData.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityDepartmentDetail
    {
        public SecurityDepartmentDetail()
        {
            this.SecurityPersonnelDetails = new HashSet<SecurityPersonnelDetail>();
        }
    
        public int SecurityDepartmentID { get; set; }
        public string SecurityDepartmentName { get; set; }
        public string SecurityDepartmentArea { get; set; }
    
        public virtual ICollection<SecurityPersonnelDetail> SecurityPersonnelDetails { get; set; }
    }
}
