//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityApplicationData.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityPersonnelDetail
    {
        public long SecurityPersonnelID { get; set; }
        public string SecurityPersonnelName { get; set; }
        public short SecurityPersonnelAge { get; set; }
        public string SecurityPersonnelAddress { get; set; }
        public Nullable<int> SecurityDepartmentID { get; set; }
    
        public virtual SecurityDepartmentDetail SecurityDepartmentDetail { get; set; }
    }
}
